apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: manual-infrastructure-deploy-
  namespace: argocd
spec:
  workflowTemplateRef:
    name: cluster-infrastructure-deploy
  arguments:
    parameters:
    - name: git-repo
      value: "{{GIT_REPO}}"
    - name: git-revision
      value: "{{GIT_REVISION}}"
    - name: environment
      value: "{{ENVIRONMENT}}"
    - name: dry-run
      value: "{{DRY_RUN}}"