apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret
  namespace: argo-events
spec:
  encryptedData:
    secret: AgBVNEs2KYCNMVmY2eQ8seYzpoBSarophML6d0WbuMkp11kDZC6nzbXmG7qS5QInsv1V9tB6QRiYFV7DZsV9wvRTBjklcI62zRTLDx2G3L0Qw6LPJ4z32FgtaXw7+SfRUkwTvuTPhvv9osbKIEfxO0im+pMX0iVlCgHwE2U5+2AtH0gJf8AguVZka4dql3/rarogruUGq8BzHMadmRLq2N3VTbCQ8FmPZcJfOxCHkQ/B8eh6HR3Pt/H3UiEC5Px5hXN5Yn8/EibzriSInvLz2eySVut5Lfc3W5XRwDIgXjl1Lmbcf46JWS2gpo+QlH2SE7FCfRLLyGqQzwvtjmznWcATrFj2Yiejl3oOHAn6RbKEDUzqU51zbFV9lKfnUZAINrFfuKWviUt09JXy2VED7iR+4HRW0z0FK8gTD3dUWjJHt/+bjGQXqCoJc/AG8bn0oq9yz9duKEwYzGFwGN3XOgqr/tcK8IFM16r+LY/KFGZ2YVxsEHF7Rjcq5d3LOBdpbmKphqYugl2D24Dy530xdYvSwoKirMfqWYRkL74az09Ej1hdOAFtvVYgJtzNOjZ6mwk1BwgXt+dOin5dibItvHZ+rZQogqyL1YqFicIIxROMgjWO0eRhx87AxN5en+jdsHbj/wFAH4p19+j16SXti29M/2Y/SjG0xtRAbIGk/Kj3zhlsFelsXpb5sCas5CDxXHgBCYFU8zCI8M3CEQwA1m6eiQcatGbu9GmxjoG4xGJ6gY1uocebPP5q8k7WQK2p5NtHCFdBbXylQGXn57s1gnTB
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret
      namespace: argo-events
---
