apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-webhook-secret
  namespace: argo-events
spec:
  encryptedData:
    secret: AgBhfG2xbKjLe84c+evOhi//X2WwrFRlf2HgbDHbqfYc3nu0M8fSG8hmG9nJaMbtibuuk5bm9RD4TJivVBEhBaED3+CKoWoT3Vbta/1pEvgFClB4bslLclhLMf3LAsjS/1nkeQ46kadopBLWy/iy0MWpLEMQuwCGiZ3+TL8aX3egcaidqREuFcGgoMr3VYeC79nKt9ayMhRtU52zQdVm3xCLyUnbXPOy3S+8Q76ZVEqaCtcSHkxX588Myz4dp9PzYj8naLUCdphJvTz4W/19JCPu4kJlizd4cbnWAj0tXo9fQY1NZn95Gq5KHnjP5aYtdg826Hsjyxh+DIpE1n/njuJPFC/9xSCEYN7U1VXX3H/tJ1lT35Nh8J6biID1lh5h8MvErIooUKsMuqXalb04vxrLtTOcYZ2BMfc/OGzGM3rDqi/DZMJhVNPcSzGSznt6O2BL9k72LC1JP+D6GYQO1rZAz/x5a8dvo4zKUtWQn9/y7pVcbCgWCcKZTw92d3LINqO1ZE7WCcWNk4xVeEH88K7D8wXjfJixpeeg7LxtMSzDrWLylzR3BqbUdb84wtRitq4jlNUk9F0v7FIhTERYnUqcOVJZgP/g4rXVf2649dRH8UYP1jB/gCNkmSIZj/3OViqBgeyL9+heQOxfPTtlfBnrptWc03XR4p9Nt6k4Bh/8GMxrAaC/IuO0eA33KnmCB4EUL7NiR4m05MnYiB6xQdymSkgbSXYYe2BCCjXRH8NxNnco6OixwyD2OXEUaGxf27fdYIQ1T1QrDP0Q+oBwiMGg
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-webhook-secret
      namespace: argo-events
---
